### ISSUE TITLE
Error while loading shared libraries: libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/sv-callers#22]
```
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```
```
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

bcftools (1.9, h47928c2_2, bioconda)
- curl (7.64.0, h646f8bb_2, conda-forge)
   - libcurl (7.64.0, h541490c_2, conda-forge)
      - openssl (1.1.1a, h14c3975_1000, conda-forge) -> downgrade to v1.0

samtools v1.9 (h91753b0_5, bioconda)

**Comment by andhena** [comment]
[(https://github.com/bioconda/bioconda-recipes/issues/12100)](url)
I hope it helps
`conda install -c bioconda bcftools openssl=1.0`
OR
`conda install -c bioconda samtools openssl=1.0`

**Comment by praneetha92** [comment]
Hi @arnikz 
I encountered this error, i thought of downgrading openssl but i found out doing so might be risky, can you please help me out. Thanks in advance.
Ubuntu :- 20.04

(base) india@india-HP-ProBook-445-G1:~$ bcftools
bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
(base) india@india-HP-ProBook-445-G1:~$ **conda list**
# packages in environment at /home/india/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
**bcftools                  1.9                  h4da6232_0    bioconda/label/broken**
bedtools                  2.27.1               he941832_2    bioconda/label/cf201901
blasr                     5.2p1                         0    bioconda/label/cf201901
brotlipy                  0.7.0           py38h8df0ef7_1001    conda-forge
bwa                       0.7.17               hed695b0_7    bioconda
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.11.8            ha878542_0    conda-forge
cairo                     1.16.0            h9f066cc_1006    conda-forge
certifi                   2020.11.8        py38h578d9bd_0    conda-forge
cffi                      1.14.3           py38h1bdcb99_1    conda-forge
chardet                   3.0.4           py38h924ce5b_1008    conda-forge
conda                     4.9.2            py38h578d9bd_0    conda-forge
conda-package-handling    1.7.2            py38h8df0ef7_0    conda-forge
cryptography              3.2.1            py38h7699a38_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
falcon-kit                1.8.1                    pypi_0    pypi
falcon-phase              1.2.0                    pypi_0    pypi
falcon-unzip              1.3.7                    pypi_0    pypi
fontconfig                2.13.1            h7e3eb15_1002    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
future                    0.18.2           py38h578d9bd_2    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
harfbuzz                  2.7.2                ha5b49bf_1    conda-forge
hdf5                      1.12.0          nompi_h1022a3e_102    conda-forge
htslib                    1.10.2               hd3b49d5_1    bioconda
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.3.1            py38h82cb98a_0    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.35.1               hed1e6ac_0    conda-forge
libblas                   3.9.0                2_openblas    conda-forge
libcblas                  3.9.0                2_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
libgfortran5              9.3.0               he4bcb1c_17    conda-forge
libglib                   2.66.2               hbe7bbb4_0    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                2_openblas    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                h4f3a223_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
matplotlib-base           3.3.3            py38h5c7f4ab_0    conda-forge
minimap2                  2.15                 ha92aebf_0    bioconda/label/cf201901
mummer4                   4.0.0beta2      pl526hfc679d8_3    bioconda/label/cf201901
mutmap                    2.2.0                      py_0    bioconda
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.5                        py_0    conda-forge
nim-falcon                0.0.0                         0    bioconda/label/cf201901
numpy                     1.19.4           py38hf0fd68c_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjdk                   11.0.8               hacce0ff_0    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pandas                    1.1.4            py38h0ef3d22_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pb-assembly               0.0.8                         0    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda/label/cf201901
pb-falcon                 2.2.4            py38h1bd3507_1    bioconda
pb-falcon-phase           0.1.0                h8e334b0_1    bioconda
pbgcpp                    2.0.0                         0    bioconda
pbmm2                     1.4.0                h56fc30b_0    bioconda
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
pillow                    8.0.1            py38h70fbd49_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycosat                   0.6.3           py38h8df0ef7_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysam                     0.16.0.1         py38hbdc2ae9_1    bioconda
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
python                    3.8.6           h852b56e_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-edlib              1.3.8.post2      py38hed8969a_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda/label/cf201901
python-msgpack            0.6.1            py38hed8969a_3    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda/label/cf201901
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
qtlseq                    2.1.2                      py_0    bioconda
racon                     1.3.1                he941832_5    bioconda/label/cf201901
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.0             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.80         py38h8df0ef7_1003    conda-forge
samtools                  1.10                 h2e538c0_3    bioconda
scipy                     1.5.3            py38hb2138dd_0    conda-forge
seaborn                   0.11.0               ha770c72_1    conda-forge
seaborn-base              0.11.0             pyhd8ed1ab_1    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snpeff                    5.0                           0    bioconda
sqlite                    3.33.0               h4cf870e_1    conda-forge
statsmodels               0.12.1           py38h0b5ebd8_1    conda-forge
tabix                     0.2.6                ha92aebf_0    bioconda
tk                        8.6.10               hed695b0_1    conda-forge
tornado                   6.1              py38h25fe258_0    conda-forge
tqdm                      4.52.0             pyhd3deb0d_0    conda-forge
trimmomatic               0.39                          1    bioconda
urllib3                   1.25.11                    py_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxtst              1.2.3             h516909a_1002    conda-forge
xorg-recordproto          1.14.2            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

**Comment by praneetha92** [comment]
Hi @arnikz
I encountered this error, i thought of downgrading openssl but i found out doing so might be risky, can you please help me out. Thanks in advance.
Ubuntu :- 20.04

bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

 **conda list**
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
**bcftools                  1.9                  h4da6232_0    bioconda/label/broken**
bedtools                  2.27.1               he941832_2    bioconda/label/cf201901
blasr                     5.2p1                         0    bioconda/label/cf201901
brotlipy                  0.7.0           py38h8df0ef7_1001    conda-forge
bwa                       0.7.17               hed695b0_7    bioconda
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.11.8            ha878542_0    conda-forge
cairo                     1.16.0            h9f066cc_1006    conda-forge
certifi                   2020.11.8        py38h578d9bd_0    conda-forge
cffi                      1.14.3           py38h1bdcb99_1    conda-forge
chardet                   3.0.4           py38h924ce5b_1008    conda-forge
conda                     4.9.2            py38h578d9bd_0    conda-forge
conda-package-handling    1.7.2            py38h8df0ef7_0    conda-forge
cryptography              3.2.1            py38h7699a38_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
falcon-kit                1.8.1                    pypi_0    pypi
falcon-phase              1.2.0                    pypi_0    pypi
falcon-unzip              1.3.7                    pypi_0    pypi
fontconfig                2.13.1            h7e3eb15_1002    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
future                    0.18.2           py38h578d9bd_2    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
harfbuzz                  2.7.2                ha5b49bf_1    conda-forge
hdf5                      1.12.0          nompi_h1022a3e_102    conda-forge
htslib                    1.10.2               hd3b49d5_1    bioconda
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.3.1            py38h82cb98a_0    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.35.1               hed1e6ac_0    conda-forge
libblas                   3.9.0                2_openblas    conda-forge
libcblas                  3.9.0                2_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
libgfortran5              9.3.0               he4bcb1c_17    conda-forge
libglib                   2.66.2               hbe7bbb4_0    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                2_openblas    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                h4f3a223_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
matplotlib-base           3.3.3            py38h5c7f4ab_0    conda-forge
minimap2                  2.15                 ha92aebf_0    bioconda/label/cf201901
mummer4                   4.0.0beta2      pl526hfc679d8_3    bioconda/label/cf201901
mutmap                    2.2.0                      py_0    bioconda
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.5                        py_0    conda-forge
nim-falcon                0.0.0                         0    bioconda/label/cf201901
numpy                     1.19.4           py38hf0fd68c_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjdk                   11.0.8               hacce0ff_0    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pandas                    1.1.4            py38h0ef3d22_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pb-assembly               0.0.8                         0    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda/label/cf201901
pb-falcon                 2.2.4            py38h1bd3507_1    bioconda
pb-falcon-phase           0.1.0                h8e334b0_1    bioconda
pbgcpp                    2.0.0                         0    bioconda
pbmm2                     1.4.0                h56fc30b_0    bioconda
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
pillow                    8.0.1            py38h70fbd49_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycosat                   0.6.3           py38h8df0ef7_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysam                     0.16.0.1         py38hbdc2ae9_1    bioconda
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
python                    3.8.6           h852b56e_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-edlib              1.3.8.post2      py38hed8969a_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda/label/cf201901
python-msgpack            0.6.1            py38hed8969a_3    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda/label/cf201901
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
qtlseq                    2.1.2                      py_0    bioconda
racon                     1.3.1                he941832_5    bioconda/label/cf201901
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.0             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.80         py38h8df0ef7_1003    conda-forge
samtools                  1.10                 h2e538c0_3    bioconda
scipy                     1.5.3            py38hb2138dd_0    conda-forge
seaborn                   0.11.0               ha770c72_1    conda-forge
seaborn-base              0.11.0             pyhd8ed1ab_1    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snpeff                    5.0                           0    bioconda
sqlite                    3.33.0               h4cf870e_1    conda-forge
statsmodels               0.12.1           py38h0b5ebd8_1    conda-forge
tabix                     0.2.6                ha92aebf_0    bioconda
tk                        8.6.10               hed695b0_1    conda-forge
tornado                   6.1              py38h25fe258_0    conda-forge
tqdm                      4.52.0             pyhd3deb0d_0    conda-forge
trimmomatic               0.39                          1    bioconda
urllib3                   1.25.11                    py_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxtst              1.2.3             h516909a_1002    conda-forge
xorg-recordproto          1.14.2            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

**Comment by arnikz** [comment]
Hi @praneetha92,

I think, you've tested an older version of _sv-callers_ (with pinned _openssl_), please use the latest `1.1.2`. Also, you might need to install `bc` on your machine (see #44).
