### ISSUE TITLE
Update test data for the workflow

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/sv-callers#41]
Add a proposal for a new [data release](https://doi.org/10.5281/zenodo.2663307) (v1.2.0) to the wiki. Perhaps we should also consider artificial data generated by [sv-gen](https://github.com/GooglingTheCancerGenome/sv-gen/).
- [x] select input data
- [x] run the _sv-callers_ workflow on
   - [X] NA24385/HG002 sample
   - [x] CHM1_CHM13 sample !!! [Review](https://github.com/GooglingTheCancerGenome/sv-callers/issues/41#issuecomment-617844339) LUMPY data !!!
- [x] update Jupyter [Notebooks](https://github.com/GooglingTheCancerGenome/notebooks/tree/nb-sv-callers-1.2.0)
  - [x] example_1
  - [x] example_2
- [x] document [reference genomes](https://gatk.broadinstitute.org/hc/en-us/articles/360035890711-GRCh37-hg19-b37-humanG1Kv37-Human-Reference-Discrepancies)  used !!! CROSS-CHECK PROVENANCE !!!
   - [x] NA12878 - `b37_human_decoy_reference.fasta` [how the FASTA file was created step-by-step](https://github.com/GooglingTheCancerGenome/sv-callers/wiki/Building-the-b37-human-decoy-reference-genome) (`b57a59692e6d189eb99fce8d14589def`)
Note: the [b37 reference genome](https://gatk.broadinstitute.org/hc/en-us/articles/360035890711-GRCh37-hg19-b37-humanG1Kv37-Human-Reference-Discrepancies#b37) of the Broad Institute, confusingly named `Homo_sapiens_assembly19.fasta`, is not reachable from the [Google Cloud](https://console.cloud.google.com/storage/browser/_details/broad-references/hg19/v0/Homo_sapiens_assembly19.fasta).
   - [x] NA24385 - `hs37d5.fa` (`12a0bed94078e2d9e8c00da793bbc84e` after decompress; `ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz`)
   - [x] CHM1_CHM13 - [Homo_sapiens_assembly19.fasta](http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta) (`886ba1559393f75872c1cf459eb57f2d`)
   - [x] COLO829 - `Homo_sapiens.GRCh37.GATK.illumina.fasta` (`be672f01428605881b2ec450d8089a62`) is in fact composed of the chromosomes (1 to 22, X, Y and MT) downloaded from Ensembl (`ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/`), concatenated and with the header containing only the chromosome name (for instance '1' for chromosome 1).
- [x] create a ZIP archive from I/O files and upload the archive to Zenodo
  - data path: `/project/gcg/Data/notebooks-data`

**Comment by lsantuari** [comment]
For the benchmark data, we refer to the [Wiki](https://github.com/GooglingTheCancerGenome/sv-callers/wiki/Benchmark-data).

**Comment by lsantuari** [comment]
We will leave out the artificial data, because of space constraints and lack of specific repositories.

**Comment by lsantuari** [comment]
I generated the alignment metrics with Picard tools for the samples CHM1_CHM13_2 and CHM1_CHM13_3 ([Wiki](https://github.com/GooglingTheCancerGenome/sv-callers/wiki/Benchmark-data)).
They are quite similar, but CHM1_CHM13_2 has higher coverage (higher number of mapped read pairs) and better overall base qualities.
I will upload the metrics to a 'testdata' folder in the ‘sandbox’ branch of sv-callers, if it is fine with you.

**Comment by arnikz** [comment]
What's the data size?

**Comment by lsantuari** [comment]
Only 220K in total.

**Comment by arnikz** [comment]
That's fine.

**Comment by lsantuari** [comment]
We can add [this notebook](https://github.com/GooglingTheCancerGenome/CNN/blob/iss32/notebooks/benchmark/Benchmark.ipynb) to sv-callers.

**Comment by arnikz** [comment]
Let me know when I can transfer the CHM1_CHM13 data (after fixing `delly.vcf` and `all.vcf` files).

**Comment by lsantuari** [comment]
The CHM1_CHM13_2 is now ready for transfer.

**Comment by arnikz** [comment]
Any news regarding the NA24385/HG002 data analysis?

**Comment by lsantuari** [comment]
I am half way through the run on the HPC. It should finish in a couple of days.

**Comment by arnikz** [comment]
I've updated both example [notebooks](https://github.com/GooglingTheCancerGenome/notebooks/tree/nb-sv-callers-1.2.0). The 2nd one is work in progress (see lines with TODO). Any suggestions to address these?

**Comment by lsantuari** [comment]
For loading the VCF files you can use the [load_vcf](https://github.com/GooglingTheCancerGenome/CNN/blob/iss32/notebooks/benchmark/Benchmark.ipynb) function.

**Comment by arnikz** [comment]
The selection of input data including the import of truth sets (in `.vcf.gz`, `.bed` and `.bedpe`) has been greatly simplified in the [example_2](https://github.com/GooglingTheCancerGenome/notebooks/blob/9e383485ab2fdf9d8205d910c2247332a670dba1/example_2/sv_evaluate.ipynb) notebook. The LUMPY callset of the CHM1_CHM3 sample includes DUP, INV and BND but not DELs (related to [this](https://github.com/arq5x/lumpy-sv/issues/160) issue?). Moreover, other callers have low recall for this sample (see the [wiki repo](https://github.com/GooglingTheCancerGenome/sv-callers.wiki/files/testdata/metrics_CHM1_CHM13_dbVar_nstd137.csv)).

**Comment by arnikz** [comment]
Add [here](https://github.com/GooglingTheCancerGenome/sv-callers/wiki/Benchmark-data) command(s) to amend the NA24385 BAM file (relates to #42).

**Comment by arnikz** [comment]
> The LUMPY callset of the CHM1_CHM3 sample includes DUP, INV and BND but not DELs (related to [this](https://github.com/arq5x/lumpy-sv/issues/160) issue?).

@lsantuari any news regarding this?

**Comment by lsantuari** [comment]
@arnikz I only have the following points regarding the notebooks:
1. In the notebook example_2:sv_evaluate we should only consider DELs longer than 50 bp, as they are commonly defined in latest literature.
2. Strangely, DELLY seems to have positive svLen for some DEL entries and negative svLen for other DEL entries...

**Comment by arnikz** [comment]
>     1. In the notebook example_2:sv_evaluate we should only consider DELs longer than 50 bp, as they are commonly defined in latest literature.
> 
currently, this is set dynamically given the truth set [11] but could be set by a user

`[3] min.svlen <- -1`

>     2. Strangely, DELLY seems to have positive svLen for some DEL entries and negative svLen for other DEL entries...

Yes, however, this is handled by `abs()` prior filtering the callsets:

`[13] gr <- gr[abs(gr$svLen) >= min.svLen]`

I've also added to the [summaries](https://github.com/GooglingTheCancerGenome/notebooks/commit/3c55a4f576bc71361f5a213d24144a6274ea4aaa). OK?
