### ISSUE TITLE
Change the semantics for naming samples

### ISSUE THREAD

**Issue by arnikz** [GooglingTheCancerGenome/sv-callers#5]
The workflow supports both germline and somatic modes. In the [samples.csv](https://github.com/GooglingTheCancerGenome/sv-callers/blob/dev/snakemake/samples.csv) file (and related code) the column names TUMOR/NORMAL are for paired samples (somatic) and TUMOR are for a single sample (germline).
Would it be better to rename to SAMPLE1/SAMPLE2 and to SAMPLE instead?

**Comment by lsantuari** [comment]
I would use the generic naming of SAMPLE1/SAMPLE2 for two samples runs and SAMPLE for single sample runs. However, I would add as a note that in the case of Tumor/Normal comparisons, SAMPLE1 must be the Tumor sample and SAMPLE2 must be the Normal sample.

**Comment by arnikz** [comment]
The header of the `samples.csv` file was changed to PATH,SAMPLE1,SAMPLE2. Paired sample runs use both SAMPLE1/SAMPLE2 columns while the single sample runs use SAMPLE1 only (SAMPLE2 is left empty).
