### ISSUE TITLE
GermlineSV_calling in WGS (centos7 local machine)

### ISSUE THREAD

**Issue by nitha26** [GooglingTheCancerGenome/sv-callers#50]
Hi,

I tried TEST RUN of GERMLINE sv calling (mode=s) by sv-callers for 2 samples. But it was not successful, it kept on running for more 30hrs. The ``delly call BND`` was running for >40hrs so I  killed the jobs. 

1. what is the importance of using **exclude_regions: 1** file. Whether it's **only used to speed up** the analysis. (Whether it is used for detecting exact breakpoint in reads?

2. The  exclude_regions **(data/ENCFF001TDO.bed)** is particular for reference genome version type? I had seen the data set you had used the **hg19** version genome file? **All my samples are aligned using GRCh38 version.** 

3. Incase if i don't have ENCFF001TDO.bed for GRCh38 reference and when I edit in  **analysis.yaml file as exclude_region=0** whether this modification creates an accuracy problem in GERMLINE svcalling? Do you provide any excluded region files for hg38?

4. In delly they provide exclude region file for hg38 in .tsv (human.hg38.excl.tsv) can this file can be used in sv-caller insted of ENCFF001TDO.bed?  

5. Could you please brief me on the **files to be modified** before running sv-callers for **germlineSV calling**? And particularly in editing samples.csv (GERMLINE). Eg: Please provide an idea of how the **.csv file looks for 3 samples in GERMLINE svcalling.**  

If you could provide detailed steps separately for 1. GermlineSV calling (WGS) 2. SomaticSV (WGS) calling in README it will be very useful for tool USERS to understand the workflow.  

Thank you.

**Comment by arnikz** [comment]
> I tried TEST RUN of GERMLINE sv calling (mode=s) by sv-callers for 2 samples. But it was not successful, it kept on running for more 30hrs. The `delly call BND` was running for >40hrs so I killed the jobs.

We came across Delly jobs that ran up to 5 days but completed successfully. So, your run was "not successful" because you didn't wait and canceled it prematurely :wink:

>     1. what is the importance of using **exclude_regions: 1** file. Whether it's **only used to speed up** the analysis. (Whether it is used for detecting exact breakpoint in reads?

It's meant to exclude genomic regions with anomalous mappability (so less data, faster analysis).

>     2. The  exclude_regions **(data/ENCFF001TDO.bed)** is particular for reference genome version type? I had seen the data set you had used the **hg19** version genome file? **All my samples are aligned using GRCh38 version.**

Make change(s) in the config accordingly.
 
>     4. In delly they provide exclude region file for hg38 in .tsv (human.hg38.excl.tsv) can this file can be used in sv-caller insted of ENCFF001TDO.bed?

Yes, provided that your exclusion list is BED formatted.

>     5. Could you please brief me on the **files to be modified** before running sv-callers for **germlineSV calling**? And particularly in editing samples.csv (GERMLINE). Eg: Please provide an idea of how the **.csv file looks for 3 samples in GERMLINE svcalling.**

Related to #51.

**Comment by nitha26** [comment]
Thank you for the explanation. 
I have one doubt, using Delly (0.8.3) with all default options, I had done germline variant calling for 82 samples in a computing system.  All the jobs were completed within 16hrs by utilizing the available cores. But in svcallers, germline variant calling delly consumes more time compared to other tools in svcaller. For 3 samples the delly (BND) calling was kept on running for  3 days,  so I had to kill the jobs. Could you give me some information regarding the time-consuming in delly inside svcaller.

Thanks.

**Comment by arnikz** [comment]
The current version of the _sv-caller_ relies on an older Delly version (0.7.7), which might (partially) explain your doubt.

https://github.com/GooglingTheCancerGenome/sv-callers/blob/8415db11b0d8b9dd705ab8bcac3737e92b4f8e57/snakemake/environment.yaml#L7

Moreover, comparing the two runs without more details (e.g. Delly command line(s), input data, number of cores used etc.) is rather elusive. See the commands used in this mode
https://github.com/GooglingTheCancerGenome/sv-callers/blob/8415db11b0d8b9dd705ab8bcac3737e92b4f8e57/snakemake/rules/delly.smk#L69-L119

**Comment by nitha26** [comment]
Thank you for your time and consideration. While in previous run, we had allocated 36 threads (edited delly.smk as well as analysis.yml)  for delly germline calling it was time consuming. Then I tried to change delly version to 0.8.3 and ran the analysis still the issue exists (i don't know whether it is proper way to do). I will keep checking.

**Comment by arnikz** [comment]
I'm afraid not. Please read carefully
https://github.com/GooglingTheCancerGenome/sv-callers/blob/8415db11b0d8b9dd705ab8bcac3737e92b4f8e57/snakemake/analysis.yaml#L53
including the [Table 1](https://peerj.com/articles/8214/#table-1) legend. As mentioned earlier, Delly version(s) >0.7.7 has NOT been tested with the current setup.

**Comment by nitha26** [comment]
Thank you for the clarification.
