### ISSUE TITLE
GermlineSV  Final Genotype Merged callsets

### ISSUE THREAD

**Issue by nitha26** [GooglingTheCancerGenome/sv-callers#51]
**GermlineSV calling**: LOCAL MACHINE  

I tried the following things:  

Input Data: sample_1, sample_2 

**Edited File:**  

/sv-callers/snakemake/samples.csv  

for 2 samples I had edited as following  

-1-

**PATH,SAMPLE1,SAMPLE2  
data/bam/3,chr22_1,chr22_2** 

(But when i edit like this, the job is running for 1 sample and only 1 folder is created, so tried 2nd way) 

Another way I tried to edit samples.csv as 

-2nd way-
**PATH,SAMPLE1,SAMPLE2  
data/bam/3,chr22_1  
data/bam/3,chr22_2**  

after this **correction in samples.csv file**, executed the command "``snakemake -C echo_run=0 mode=s enable_callers="['manta','delly','lumpy','gridss']" --use-conda"``

**Results:**
**/sv-callers/snakemake/data/bam/3**
chr22_1(FOLDER1)  chr22_1.bam  chr22_1.bam.bai  chr22_2 (FOLDER2)  chr22_2.bam  chr22_2.bam.bai  N3.bam  N3.bam.bai  sample_testrun  T3.bam  T3.bam.bai  

**DOUBTS:**  
1. inside these folders chr22_1(FOLDER1) chr22_2(FOLDER2) it had generated "all.vcf" in each corresponding folders. all.vcf of all callers are SV are generated (Will sv-caller perform merge  
2. I could not find the Final joint calling VCF file for 2 samples, I have information for only in individual sample wise.  

Eg: If I run Delly separately,  the final merged genotype VCF contains information of all 2samples #CHROM POS .....INFO Sample1 Sample2. Similar results I got when I run MANTA diploid_svcalling.vcf (contains information of 2 samples)  

But when I run the sv-callers for 2 sample test run, am not getting the combined genotype callset information of  2samples  in any callers "all.vcf". The information is seen as sample wise.    

I think I am doing mistakes while editing the **samples.csv** file for GERMLINE svcalling. could you please tell me how to edit **samples.csv** file particularly for germline svcalling.  

Thanks for the help.

**Comment by arnikz** [comment]
> **GermlineSV calling**: LOCAL MACHINE
> 
> I tried the following things:
> 
> Input Data: sample_1, sample_2
> 
> **Edited File:**
> 
> /sv-callers/snakemake/samples.csv
> 
> for 2 samples I had edited as following
> 
> -1-
> 
> **PATH,SAMPLE1,SAMPLE2 data/bam/3,chr22_1,chr22_2**
> 
> (But when i edit like this, the job is running for 1 sample and only 1 folder is created, so tried 2nd way)

If you ran in `mode=s` then the `SAMPLE2` column is ignored in the _single sample_ mode; paired samples (e.g., tumor/normal) are meant for `mode=p` (somatic analysis) as described in the README.

> 
> Another way I tried to edit samples.csv as
> 
> -2nd way-
> **PATH,SAMPLE1,SAMPLE2 data/bam/3,chr22_1 data/bam/3,chr22_2**
> 
> after this **correction in samples.csv file**, executed the command "`snakemake -C echo_run=0 mode=s enable_callers="['manta','delly','lumpy','gridss']" --use-conda"`
> 
> **Results:**
> **/sv-callers/snakemake/data/bam/3**
> chr22_1(FOLDER1) chr22_1.bam chr22_1.bam.bai chr22_2 (FOLDER2) chr22_2.bam chr22_2.bam.bai N3.bam N3.bam.bai sample_testrun T3.bam T3.bam.bai
>

As expected when running in the `mode=s` with two BAMs (one per line).

> **DOUBTS:**
> 
>     1. inside these folders chr22_1(FOLDER1) chr22_2(FOLDER2) it had generated "all.vcf" in each corresponding folders. all.vcf of all callers are SV are generated (Will sv-caller perform merge
>
>     2. I could not find the Final joint calling VCF file for 2 samples, I have information for only in individual sample wise.
> 

Correct (see [here](https://github.com/GooglingTheCancerGenome/sv-callers/blob/master/doc/sv-callers_single.svg)).

> Eg: If I run Delly separately, the final merged genotype VCF contains information of all 2samples #CHROM POS .....INFO Sample1 Sample2. Similar results I got when I run MANTA diploid_svcalling.vcf (contains information of 2 samples)
> 
> But when I run the sv-callers for 2 sample test run, am not getting the combined genotype callset information of 2samples in any callers "all.vcf". The information is seen as sample wise.
>

The workflow performs germline analysis of N samples in parallel but only in this sample-wise manner (or _single sample_ mode). Merging VCFs across samples remains up to you.

**Comment by nitha26** [comment]
Thank you.
