### ISSUE TITLE
HPC cluster usage 

### ISSUE THREAD

**Issue by nitha26** [GooglingTheCancerGenome/sv-callers#52]
Hi @arnikz ,

When we processed the sv-caller for 3 samples as a test run in  **slurm based script** we found that the jobs are getting scheduled in the single node [i.e gpunode]. The takes more time than the required time to process the data-set, with **hyperthreading enabled. Note openmp & pyflow has been enabled in conda env.**  

**Doubts:-**  

1. for three samples maximum execution of jobs should be 14 are lesser than that?   **What this falg ``--jobs 14`` indicates?**
2. can **xenon scheduler** be mapped to **various compute nodes**?  
3. can the --max-run-time and location for slurm be changed?  

**jobscript used :-**

``#!/bin/bash`` 

``SCH=slurm   # or gridengine  
snakemake -C echo_run=0 mode=s enable_callers="['manta','delly','lumpy','gridss']" --use-conda --latency-wait 30 --jobs 14 \
--cluster 'xenon scheduler $SCH --location local:// submit --name smk.{rule} --inherit-env --cores-per-task {threads} --max-run-time 1440 --max-memory {resources.mem_mb} --working-directory . --stderr stderr-%j.log --stdout stdout-%j.log' &>smk.log&``

What may be the problem? could you help with this issue?

Thank you in advance.

**Comment by arnikz** [comment]
>     1. for three samples maximum execution of jobs should be 14 are lesser than that?   **What this falg `--jobs 14` indicates?**

Analysing one sample (or pair) per line spawns 14 workflow jobs (as documented in README). For snakemake command-line args refer to [here](https://snakemake.readthedocs.io/en/stable/executing/cli.html#all-options).
 
>     2. can **xenon scheduler** be mapped to **various compute nodes**?

Related to #53 

>     3. can the --max-run-time and location for slurm be changed?

Both are command-line args so their values can be changed according to your needs.

**Comment by nitha26** [comment]
Thank you.
