### ISSUE TITLE
HPC Usage issue on slurm ?

### ISSUE THREAD

**Issue by Navin-techi** [GooglingTheCancerGenome/sv-callers#53]
**is there a way to mention nodelist / specific nodes to run the jobs on slurm for the sv-callers using xenon schedulers ?**

_snakemake -C echo_run=0 mode=s enable_callers="['manta','delly','lumpy','gridss']" --use-conda --latency-wait 30 --jobs 14
--cluster 'xenon scheduler $SCH --location local:// submit **--queue {slurm-partition-name}** --name smk.{rule} --inherit-env --cores-per-task {threads} --max-run-time 1 --max-memory {resources.mem_mb} --working-directory . --stderr stderr-%j.log --stdout stdout-%j.log' &>smk.log&_

**Comment by Navin-techi** [comment]
snakemake -C echo_run=0 mode=s enable_callers="['manta','delly','lumpy','gridss']" --use-conda --latency-wait 30 --jobs 14 \
--cluster 'xenon scheduler $SCH --location local:// submit **--queue {slurm-partition-name}** --name smk.{rule} --inherit-env --cores-per-task {threads} --max-run-time 1 --max-memory {resources.mem_mb} --working-directory . --stderr stderr-%j.log --stdout stdout-%j.log' &>smk.log&

**Comment by sverhoeven** [comment]
You can use `--scheduler-argument` to set a nodelist.
For example to request only `node-0` use:

_xenon scheduler $SCH --location local:// submit --queue {slurm-partition-name} \ 
 --name smk.{rule} --inherit-env --cores-per-task {threads} --max-run-time 1 \
 --max-memory {resources.mem_mb} --working-directory . --stderr stderr-%j.log --stdout stdout-%j.log \
 **--scheduler-argument=--nodelist=node-0**_

**Comment by nitha26** [comment]
@sverhoeven @arnikz  we had tried these comments ``snakemake -C echo_run=0 mode=s enable_callers="['manta','delly','lumpy','gridss']" --use-conda --latency-wait 30 --jobs 14 --cluster 'xenon scheduler slurm --location local:// submit --queue compute --name smk.{rule} --inherit-env --cores-per-task 36 --tasks-per-node 1 --max-run-time 1440 --queue compute --working-directory . --stderr stderr-%j.log --stdout stdout-%j.log --scheduler-argument=--nodelist=/gpfs/data/user/nodel_1'``
still we were not able to split up the jobs in different nodes.  we tried by giving ``--tasks-per-node 3`` but still the job was running in a single node. (in our nod_1 list we had mentioned the nodes to be used).
Thanks you.

**Comment by sverhoeven** [comment]
You have to use `--tasks 3 --tasks-per-node 1` to get 3 nodes and the command executed once on one of the 3 nodes. 
Normally Slurm is configured to not care about cores/cpus and just assigns whole nodes to a job so I would drop `--cores-per-task 36` argument.
@jmaassen is this right?

**Comment by arnikz** [comment]
@nitha26: Before submitting to specific nodes, first, make sure your submission works with the (unmodified) configs and test data on your HPC system.

```
snakemake -C echo_run=0 mode=s enable_callers="['manta','delly','lumpy','gridss']" --use-conda --latency-wait 30 --jobs 14 --cluster "xenon scheduler slurm --location local:// submit --name smk.{rule} --inherit-env --cores-per-task {threads} --max-run-time 15 --max-memory {resources.mem_mb} --working-directory . --stderr stderr-%j.log --stdout stdout-%j.log" &>smk.log&
```
Check the status of your jobs in the queue

`watch squeue -u [username]`

You should see something like this

```
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
            194913    normal smk.dell gcg-akuz  R       0:04      1 wn-db-05
            194909    normal smk.dell gcg-akuz  R       0:07      1 wn-db-03
            194910    normal smk.dell gcg-akuz  R       0:07      1 wn-db-04
            194911    normal smk.mant gcg-akuz  R       0:07      1 wn-ha-02
            194912    normal smk.lump gcg-akuz  R       0:07      1 wn-fa-03
            194907    normal smk.grid gcg-akuz  R       0:10      1 wn-ha-01
            194908    normal smk.dell gcg-akuz  R       0:10      1 wn-db-02
            194906    normal smk.dell gcg-akuz  R       0:13      1 wn-db-01
```

Once all jobs are done, you should see something like this

```
tail smk.log
...
[Mon Nov  9 13:32:57 2020]
Finished job 0.
15 of 15 steps (100%) done
Complete log:...
```

Retrieve the job IDs from `smk.log` and query the Slurm job accounting info (e.g., _jobid_, _jobname_ and _nodelist_).

```
grep -o "'[0-9]*'" smk.log | sed "s/'//g" > jobids.txt
for i in $(cat jobids.txt); do sacct -j $i -o jobid,jobname,nodelist; done
       JobID    JobName        NodeList 
------------ ---------- --------------- 
194906       smk.delly+        wn-db-01 
194906.batch      batch        wn-db-01 
194906.exte+     extern        wn-db-01 
       JobID    JobName        NodeList 
------------ ---------- --------------- 
194907       smk.grids+        wn-ha-01 
194907.batch      batch        wn-ha-01 
194907.exte+     extern        wn-ha-01 
       JobID    JobName        NodeList 
------------ ---------- --------------- 
194908       smk.delly+        wn-db-02 
194908.batch      batch        wn-db-02 
194908.exte+     extern        wn-db-02 
       JobID    JobName        NodeList 
------------ ---------- --------------- 
194909       smk.delly+        wn-db-03 
194909.batch      batch        wn-db-03 
194909.exte+     extern        wn-db-03 
       JobID    JobName        NodeList
...
```
Clearly, the jobs were executed on different nodes (i.e., _wn-db-*_). Once this works for you, proceed by requesting specific nodes for your jobs as suggested above. Let us know how did it go.

**Comment by nitha26** [comment]
@arnikz @sverhoeven Thanks for responding to our questions. We will try the suggestions given and will get back to you.

**Comment by anand89ak** [comment]
1. We tried the same following instruction on the docker build, but found conflict with the docker slurm and system-wide slurm.
Is there any way to go around?

2. On Centos environment how to span jobs parallelly on slurm environment? (We found that it's going to a single node based execution)

**Comment by arnikz** [comment]
>     1. We tried the same following instruction on the docker build, but found conflict with the docker slurm and system-wide slurm.
>        Is there any way to go around?



> 
>     2. On Centos environment how to span jobs parallelly on slurm environment? (We found that it's going to a single node based execution)

**Comment by arnikz** [comment]
Thanks @anand89ak. Could you clarify your first point? Moreover, without additional details, logs etc. it's difficult to reproduce your issue(s). The example above shows an execution of the workflow on a real Slurm-based HPC cluster (CentOS 7.7).

**Comment by Navin-techi** [comment]
on docker : 

# COMPUTE NODES
NodeName=node-0 Procs=2 NodeAddr=127.0.0.1 Port=17001 State=UNKNOWN
NodeName=node-1 Procs=2 NodeAddr=127.0.0.1 Port=17002 State=UNKNOWN
NodeName=node-2 Procs=2 NodeAddr=127.0.0.1 Port=17003 State=UNKNOWN
NodeName=node-3 Procs=2 NodeAddr=127.0.0.1 Port=17004 State=UNKNOWN
NodeName=node-4 Procs=2 NodeAddr=127.0.0.1 Port=17005 State=UNKNOWN
PartitionName=mypartition Nodes=node-[0-4] Default=YES MaxTime=INFINITE State=UP
PartitionName=otherpartition Nodes=node-[0-2] Default=NO MaxTime=INFINITE State=UP
root@822de0dd121e:~# scontrol update partition=mypartition state=up
root@822de0dd121e:~# sinfo -a
PARTITION      AVAIL  TIMELIMIT  NODES  STATE NODELIST
mypartition*      up   infinite      5  down* node-[0-4]
otherpartition    up   infinite      3  down* node-[0-2]
root@822de0dd121e:~# slurmctld restart
root@822de0dd121e:~# sinfo -a
PARTITION      AVAIL  TIMELIMIT  NODES  STATE NODELIST
mypartition*      up   infinite      5   down node-[0-4]
otherpartition    up   infinite      3   down node-[0-2]

the node always seems to be down. is there a way to fix it ? How many such localhost entry can be added for a 36 core machine ?
