### ISSUE TITLE
Processing trios for de novo mutations

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/sv-callers#57]
This would require:
- a three columns samples.csv format with mother, father, child;
- a postprocessing step where the overlap of the SV callsets resulting from the comparisons mother-child and father-child. The overlap could be computed with StructuralVariantAnnotation (SVA)

**Comment by arnikz** [comment]
In principle, this could be done with two _sample_ columns only (see [samples.csv](https://github.com/GooglingTheCancerGenome/sv-callers/blob/master/snakemake/samples.csv)), for example

| SAMPLE1 | SAMPLE2
|---               |---
|mother1 | child1
|father1 | child1
|... |...

followed by a post-processing step.
