### ISSUE TITLE
Run this pipeline on PBS based HPC 

### ISSUE THREAD

**Issue by yangyxt** [GooglingTheCancerGenome/sv-callers#59]
Can this tool be compatible with PBS based HPC machine? 

The job scheduling system is maintained by Department-based IT staff so it is not our users' choice which job scheduling systems are available.

Pls kindly considering make PBS-pro system compatible with this workflow.

**Comment by arnikz** [comment]
Thanks for your interest. Could you share the exact name + version of your scheduler?

In principle, you could pass any job submission command directly via `snakemake --cluster "[submitcmd]"...` (e.g., via the middle-ware `"xenon scheduler torque..."`) or use `snakemake --profile` for [PBS Torque](https://github.com/Snakemake-Profiles/pbs-torque). However, we haven't tested the workflow on the latter HPC system. Give it a try and let us know about your experience.
