### ISSUE TITLE
What is the principle of merging records from multiple callers? 

### ISSUE THREAD

**Issue by yangyxt** [GooglingTheCancerGenome/sv-callers#60]
What principle is used to merge results from different callers? Is this workflow simply merging everything into one vcf by SURVIVOR? 

Thanks!

**Comment by lsantuari** [comment]
The workflow generates a file called _all.vcf_ by applying _SURVIVOR merge_ on the SV callsets generated by the four SV callers using the parameters specified in the file [analysis.yaml](https://github.com/GooglingTheCancerGenome/sv-callers/blob/300a95ddac3c77a1cac2d9e00051591d0a92292f/snakemake/analysis.yaml#L87).

**Comment by arnikz** [comment]
In addition to @lsantuari 's comment: you might also want to look at the Jupyter Notebook (part of [this](https://doi.org/10.5281/zenodo.3526703) dataset) that doesn't rely on the SURVIVOR output but rather on [StructuralVariantAnnotation](https://bioconductor.org/packages/release/bioc/html/StructuralVariantAnnotation.html) package.
