### ISSUE TITLE
bwa-mem2 + multisample sv-calling and genotyping on non-human genomes

### ISSUE THREAD

**Issue by arumds** [GooglingTheCancerGenome/sv-callers#63]
Hi,

Does sv-callers allow to **detect and genotype** SVs across multiple single samples and generate a multi-sample VCF file? If so, what would be the recommended batch size for the number of samples to use in a single analysis?

Moreover, can this be applied on non-human species? and Does it work with **BWA-MEM2** aligned BAM files and BWA-MEM2 reference indexes?

We are interested in doing a cohort based SV calling. For this, does sv-caller need all the BAMs in `.csv` file for SV calling and genotyping SVs?  Or does sv-caller allow to call SVs on single BAMs and subsequently allow to genotype across multiple samples?

**Comment by arnikz** [comment]
> Hi,
> 
> Does sv-callers allow to **detect and genotype** SVs across multiple single samples and generate a multi-sample VCF file? If so, what would be the recommended batch size for the number of samples to use in a single analysis?

> We are interested in doing a cohort based SV calling. For this, does sv-caller need all the BAMs in `.csv` file for SV calling and genotyping SVs? Or does sv-caller allow to call SVs on single BAMs and subsequently allow to genotype across multiple samples?

See https://github.com/GooglingTheCancerGenome/sv-callers/issues/51#issuecomment-721025882.
> 
> Moreover, can this be applied on non-human species? and Does it work with **BWA-MEM2** aligned BAM files and BWA-MEM2 reference indexes?
> 

See #64
