### ISSUE TITLE
Error in rule delly_p  using paired-sample SV calling 

### ISSUE THREAD

**Issue by ccastane9** [GooglingTheCancerGenome/sv-callers#65]
Hi, 

I am running a paired sample mode (mode=p) for somatic variant calling using 3 samples so that I can get a final merged vcf file for all 3 samples. I am receiving an error in the rule delly_p, although I'm not sure why. I have not changed any of the .smk rules which come with downloading sv-callers and have only changed the analysis.yaml file and samples.csv. I am also running this wrapper using conda with the command: 
$ snakemake -C echo_run=0 mode=p enable_callers="['manta','delly','lumpy','gridss']" --use-conda

My samples in the .cvs file are as such: 
/data1/path/to/BAM,sample1,sample2,sample3

The error I receive in the log file is such: 
Error in rule delly_p:
    jobid: 10
    output: /data1/EquCab/SeaHorse/SeaHorse_BAM/H1023_F_fetus_1--H1020_F_1/delly_out/delly-BND.bcf
    conda-env: /home/ccastane9/bin/sv-callers/snakemake/.snakemake/conda/5f3ee9bf
    shell:
        
        set -x

        OUTDIR="$(dirname "/data1/EquCab/SeaHorse/SeaHorse_BAM/H1023_F_fetus_1--H1020_F_1/delly_out/delly-BND.bcf")"
        PREFIX="$(basename "/data1/EquCab/SeaHorse/SeaHorse_BAM/H1023_F_fetus_1--H1020_F_1/delly_out/delly-BND.bcf" .bcf)"
        OUTFILE="${OUTDIR}/${PREFIX}.unfiltered.bcf"
        TSV="${OUTDIR}/sample_pairs.tsv"

        # fetch sample ID from a BAM file
        function get_samp_id() {
            echo "$(samtools view -H ${1} |                    perl -lne 'print ${1} if /\sSM:(\S+)/' |                    head -n 1)"
        }

        # run dummy or real job
        if [ "0" -eq "1" ]; then
            echo "/data1/EquCab/_ECA30/Equus_caballus.EquCab3.0.dna_sm.toplevel.fa /data1/EquCab/_ECA30/Equus_caballus.EquCab3.0.dna_sm.toplevel.fa.fai /data1/EquCab/SeaHorse/SeaHorse_BAM/H1023_F_fetus_1.bam /data1/EquCab/SeaHorse/SeaHorse_BAM/H1023_F_fetus_1.bam.bai /data1/EquCab/SeaHorse/SeaHorse_BAM/H1020_F_1.bam /data1/EquCab/SeaHorse/SeaHorse_BAM/H1020_F_1.bam.bai" > "/data1/EquCab/SeaHorse/SeaHorse_BAM/H1023_F_fetus_1--H1020_F_1/delly_out/delly-BND.bcf"
        else
            # use OpenMP for threaded jobs
            export OMP_NUM_THREADS=2
            #export OMP_PROC_BIND=true
            #export OMP_PLACES=threads

            # SV calling
            delly call                 -t "BND"                 -g "/data1/EquCab/_ECA30/Equus_caballus.EquCab3.0.dna_sm.toplevel.fa"                 -o "${OUTFILE}"                 -q 1 `# min.paired-end mapping quality`                 -s 9 `# insert size cutoff, DELs only`                                  "/data1/EquCab/SeaHorse/SeaHorse_BAM/H1023_F_fetus_1.bam" "/data1/EquCab/SeaHorse/SeaHorse_BAM/H1020_F_1.bam" &&
            # somatic + SV quality filtering
            #   create sample list
            TID=$(get_samp_id "/data1/EquCab/SeaHorse/SeaHorse_BAM/H1023_F_fetus_1.bam")
            CID=$(get_samp_id "/data1/EquCab/SeaHorse/SeaHorse_BAM/H1020_F_1.bam")
            printf "${TID}	tumor
${CID}	control
" > ${TSV} &&
            delly filter                 -f somatic                 -p                 -s "${TSV}"                 -o "/data1/EquCab/SeaHorse/SeaHorse_BAM/H1023_F_fetus_1--H1020_F_1/delly_out/delly-BND.bcf"                 "${OUTFILE}"
        fi
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Finished job 9.
9 of 15 steps (60%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

I did notice that in the delly_out folder, I have .bcf, .bcf.csi, .unfiltered.bcf, .unfiltered.bcf.csi output files for all sv-types EXCEPT BND. For this sv-type, I only have the .unfiltered.bcf file. Again, I'm not sure why. 
Could you please help? 
I am attaching the entire logfile produced by this run, which includes the above error message, as well as the analysis.yaml file that I've been using. I have NOT changed the snakefile which comes with downloading sv-callers. 

Thank you for any advice!
[2021-04-23T115759.946483.snakemake.log](https://github.com/GooglingTheCancerGenome/sv-callers/files/6422345/2021-04-23T115759.946483.snakemake.log)
[analysis.yaml.txt](https://github.com/GooglingTheCancerGenome/sv-callers/files/6422351/analysis.yaml.txt)
[Snakefile.txt](https://github.com/GooglingTheCancerGenome/sv-callers/files/6422353/Snakefile.txt)

**Comment by arnikz** [comment]
Hi,

Thanks for reporting this.

> 
> I am running a paired sample mode (mode=p) for somatic variant calling using 3 samples so that I can get a final merged vcf file for all 3 samples. 
> My samples in the .cvs file are as such:
> /data1/path/to/BAM,sample1,sample2,sample3

First, your `samples.csv` file doesn't seem right. All-vs-all paired sample analyses are performed as follows:

```
PATH,SAMPLE1,SAMPLE2
data/bam/,S1,S2
data/bam/,S1,S3
data/bam/,S2,S3
# data/bam/,S3,S2
```
> I did notice that in the delly_out folder, I have .bcf, .bcf.csi, .unfiltered.bcf, .unfiltered.bcf.csi output files for all sv-types EXCEPT BND

Does the issue remain if the `BND` SV type is excluded from the analysis?
https://github.com/GooglingTheCancerGenome/sv-callers/blob/300a95ddac3c77a1cac2d9e00051591d0a92292f/snakemake/analysis.yaml#L58

Could you share your input FASTA and BAM files?

**Comment by ccastane9** [comment]
Hi, 
Thank you for these suggestions! The modified script along with the modified samples.csv allowed the job to complete 100%. I'm wondering if maybe it is because I had my samples.csv file incorrect, so I will try again with adding the - BND  # translocation value back in.
