### ISSUE TITLE
Updating GRIDSS to  a newer version

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/sv-callers#69]
Modify the file environment.yaml to update [GRIDSS version](https://anaconda.org/bioconda/gridss).

**Comment by arnikz** [comment]
This issue is related to #35.

**Comment by lsantuari** [comment]
TODO: apparently GRIDSS2 needs one reference (FASTA) symlink for each running instance.

**Comment by lsantuari** [comment]
@arnikz [GitHub Actions](https://github.com/GooglingTheCancerGenome/sv-callers/runs/4805472305?check_suite_focus=true) fails because with GRIDSS2 I am using a reduced version of [ENCFF001TDO.bed](https://github.com/GooglingTheCancerGenome/sv-callers/blob/iss69/snakemake/data/ENCFF001TDO.bed) with only chr22 entries: [ENCFF001TDO.bed](https://github.com/GooglingTheCancerGenome/sv-callers/blob/iss69/snakemake/data/ENCFF001TDO.bed). If I remember well, GRIDSS2 complains if I use the full [ENCFF001TDO.bed](https://github.com/GooglingTheCancerGenome/sv-callers/blob/iss69/snakemake/data/ENCFF001TDO.bed) file. Would you suggest to update the [test](https://github.com/GooglingTheCancerGenome/sv-callers/blob/d55dc95fbd255d59629b51b1bccf0ef0941d92b2/snakemake/test_helper_functions.py#L122) function?

**Comment by arnikz** [comment]
Another option is to use the reduced file while keeping the org. filename.
