### ISSUE TITLE
Copy Number Calling

### ISSUE THREAD

**Issue by azhark2** [GooglingTheCancerGenome/sv-callers#74]
Thank you for this amazing tool. Have you considered creating a similar tool for copy number calling (using popular CNV callers such as Battenberg, FACETS, Sequenza, CNVkit, etc.)?

**Comment by arnikz** [comment]
Thanks for the suggestion. I was not planning to extend the worklow by CNV detection tools. In fact, detection of unbalanced SV types such as DEL and DUP (CNVs) is possible by the callers used (see an example study  [here](https://doi.org/10.1186/s12864-021-08082-3)). I think, one could rather extend this (modular) workflow than developing a new CNV-specific workflow.
