### ISSUE TITLE
VCF final outputs

### ISSUE THREAD

**Issue by mtinti** [GooglingTheCancerGenome/sv-callers#77]
Hi,
I'm running the paired workflow successfully, but there is something I don't understand about the all.vcf file.

My WT bam file has the unique read name set to SRRWT, and my tumour sample has the unique read name set to SRRR2. 

In all.vcf file, after the FORMAT column, there are 4 further columns, one named SRRWT, one named SRRR2, one SRRR2_1, and one named FCH5YL7CCX2_L2_wHAXPI122670-47.bam (the name of the bam file with the  SRRR2 reads, tumour sample).

All the values of the SRRWT are set to:
./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN

All the values of the SRRR2 except a few are set to:
./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN

The values of the SRRR2_1 column seem to contain valid info.

All value of the FCH5YL7CCX2_L2_wHAXPI122670-47.bam columns are set to:
./.:NaN:0:0,0:--:NaN:NaN:NaN:NAN:NAN:NAN

Can you please provide some advice?

**Comment by arnikz** [comment]
Hi,

Could you share the version of the workflow instance used? Note that the older [versions](https://github.com/GooglingTheCancerGenome/sv-callers/releases) relied merely on SURVIVOR but the more recent version (>=1.2) makes use of Viola-SV to merge/harmonize the output files of the different callers into the final `all.vcf`. Perhaps you could find some clues in the GH issues of the corresponding post-processing SV tool.
