### ISSUE TITLE
bwa-mem2 compatibility

### ISSUE THREAD

**Issue by Avramis** [GooglingTheCancerGenome/sv-callers#79]
Hi

We have some alignments that were performed using bwa-mem2 algorithm, and  we want to call all the SVs in our samples. Can the  sv-callers v1.2.2 can process the bwa-mem2 alignments?

Best
Avraam

**Comment by arnikz** [comment]
In principle, the workflow takes input BAMs and it doesn't care much how these were aligned. However, one of the callers does rely on the older _bwa-mem_ for re-alignment (see #64). Nevertheless, you could try processing your samples but we haven't tested with _bwa-mem2_.
