### ISSUE TITLE
ModuleNotFoundError in line 7 of /home/mai/sv-callers/workflow/Snakefile

### ISSUE THREAD

**Issue by mxiong2** [GooglingTheCancerGenome/sv-callers#80]
Local install on virtual machine with the following error:

**ModuleNotFoundError in line 7 of /home/mai/sv-callers/workflow/Snakefile:

No module named 'yatiml'

  File "/home/mai/sv-callers/workflow/Snakefile", line 7, in <module>

  File "/home/mai/sv-callers/workflow/helper_functions.py", line 5, in <module>

  File "/home/mai/sv-callers/workflow/validator/__init__.py", line 8, in <module>**

**Comment by arnikz** [comment]
Hi, I can't reproduce this issue given the details above. All runs fine according to the test [here](https://github.com/GooglingTheCancerGenome/sv-callers/actions). It seems that the `yatiml` module is missing from (or failed to install in) your environment but it's specified [here](https://github.com/GooglingTheCancerGenome/sv-callers/blob/master/environment.yaml#L13) for the install.
