### ISSUE TITLE
Sample entry question for germline anlaysis

### ISSUE THREAD

**Issue by mxiong2** [GooglingTheCancerGenome/sv-callers#81]
In the sample entry file, is it a requirement to enter the same sample name twice in the sample1 and sample2 column for germline analysis?

**Comment by arnikz** [comment]
Hi, you can leave out the `SAMPLE2` (3rd) column in the [`samples.csv`](https://github.com/GooglingTheCancerGenome/sv-callers/blob/master/config/samples.csv) file when performing analyses in the single-sample (germline) mode.
