### ISSUE TITLE
Error in running analysis.yml

### ISSUE THREAD

**Issue by poddarharsh15** [GooglingTheCancerGenome/sv-callers#82]
Hi,
I'm encountering an issue while attempting to run the pipeline with all callers on BAM files. The pipeline seems to be working only on the test files, and I'm unable to direct it to operate on the BAM files. Can you assist me in resolving this issue?
Thank you.

[samples4.csv](https://github.com/GooglingTheCancerGenome/sv-callers/files/13305913/samples4.csv)
[2023-11-08T165312.185346.snakemake.log](https://github.com/GooglingTheCancerGenome/sv-callers/files/13305929/2023-11-08T165312.185346.snakemake.log)

**Comment by arnikz** [comment]
Hi, just remove the leading hash (`#` indicates a comment line) from the second line in `samples4.csv` and you'll see many more jobs in the terminal or log.
